### ISSUE TITLE
Close window when it's the only available option

### ISSUE THREAD

**Issue by N0ich** [N0ich/dialogkey-DF#11]
Sometimes you open a quest window that you cannot complete, i think DK should click cancel on this to close the window

**Comment by FuriousProgrammer** [comment]
The `ignoreDisabledButtons` option is for this exact thing, actually.

The main distinction would be to ignore popup disabled buttons and *not* a quest panel with a disabled complete button, but that's a *very* niche edge case that I don't think would ever be a problem in practice; you already occasionally have to click dialogs that DialogKey doesn't like from time to time.

**Comment by FuriousProgrammer** [comment]
Ohh, I just came across this. You meant for *repeatable* quests e.g. `Gaining Acceptance` and `Gaining Even More Acceptance` in Thorium Point. I agree now.
