### ISSUE TITLE
Make DialogKey-DF WowUp (Addon manager) compatible

### ISSUE THREAD

**Issue by Wensh** [N0ich/dialogkey-DF#15]
Is your feature request related to a problem? Please describe.
Curseforge blocked Wowup addon manager, would like to manually add Github to Wowup addon manager. But DialogKey-DF releases doesn't have the required WowUP structure described here:

https://wowup.io/guide/wowup/hub

Describe the solution you'd like
Adapted zip folder structure so I can manage DialogKey-DF in WowUp

**Comment by N0ich** [comment]
It's done :) How do I add the addon to Wowup ?

**Comment by Wensh** [comment]
In WoWUp, click "Get Addons" and click "Install from URL", paste the url of this repo and that's it.

I just tested it, seems to be working, thanks
