### ISSUE TITLE
opening map issue

### ISSUE THREAD

**Issue by Squimbert** [N0ich/dialogkey-DF#24]
while waiting for resurrection at spirit healer in a battleground, pressing the default scoreboard hotkey (shifT+space) brings up the map instead of the scoreboard.

**Comment by FuriousProgrammer** [comment]
Does this still occur if you change to a different DialogKey keybind?

**Comment by FuriousProgrammer** [comment]
This is probably caused because we aren't checking for modifier keys when ignoring inputs. Should be a very simple fix, but will have to be careful if the keybind *itself* includes a modifier.

**Comment by Squimbert** [comment]
pressing the space bar (dialog key keybind) even after setting open scoreboard to a completely different key still opens the map.

**Comment by Squimbert** [comment]
i also switched the dialogkey keybind to a completely different key while scoreboard was set to shift+space and it still opened the map. it seems like no matter what the dialog key keybind will open the map if waiting for the spirit healer to resurrect me in a battleground.
