### ISSUE TITLE
Can't souldbind items in 10.0.7

### ISSUE THREAD

**Issue by Mieskoh** [N0ich/dialogkey-DF#28]
Hi, 

Since 10.0.7, I have been getting this error whenever I try to confirm a popup that would souldbind an item: 

``1x [ADDON_ACTION_FORBIDDEN] AddOn 'DialogKey' tried to call the protected function 'EndBoundTradeable()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `EndBoundTradeable'
[string "@FrameXML/StaticPopup.lua"]:3034: in function `OnAccept'
[string "@FrameXML/StaticPopup.lua"]:5316: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>
[string "=[C]"]: in function `Click'
[string "@DialogKey/main.lua"]:169: in function <DialogKey/main.lua:151>``

Thanks in advance for the help :)

**Comment by FuriousProgrammer** [comment]
Yeah this was a known incompatibility. It *should* be disabled but we must
have regressed it at some point.

**Comment by catthou** [comment]
So now that it's acknowledged, any chance of pushing a fix?

**Comment by N0ich** [comment]
Hello,
Unfortunately I'm not playing the game nor do I have an active subscription so I cannot debug the current problem. 
I'll try to have a look with a friend whenever I get the chance, but for now i'd advise to use the personnal blacklist to make sure the button isn't clicked.
The only fix we will ever be able to make will be to not try to click the button, as addons cannot click this button anyway.

**Comment by kpontussvensson** [comment]
What's the personal blacklist? Isn't that feature still disabled?
