### ISSUE TITLE
Addon calls protected function

### ISSUE THREAD

**Issue by CrenshawCoding** [N0ich/dialogkey-DF#34]
I get the following error message sometimes, Ill try and update this issue when I know what causes it!

```
38x [ADDON_ACTION_BLOCKED] AddOn 'DialogKey' tried to call the protected function 'DialogKeyFrame:SetPropagateKeyboardInput()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPropagateKeyboardInput'
[string "@DialogKey/main.lua"]:91: in function <DialogKey/main.lua:90>
[string "@DialogKey/main.lua"]:152: in function <DialogKey/main.lua:151>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

```

**Comment by FuriousProgrammer** [comment]
This should have been fixed in the most recent version of the addon, make
sure you're up to date!

**Comment by CrenshawCoding** [comment]
@FuriousProgrammer ah yea that seems to have done it. I think the way you put up releases on this repository might be off. My addon manager [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) installs version v1.4.8 as the latest version. Looking into the release of your latest version, it seems to also contain a .github folder and a .gitignore, which you may not intend to publish with the release! Why the addon manager does not the latest release correctly is weird still, I have opened [an issue](https://github.com/AcidWeb/CurseBreaker/issues/371) over there. Thanks for your work!
