### ISSUE TITLE
Github releases are broken

### ISSUE THREAD

**Issue by Numynum** [N0ich/dialogkey-DF#37]
Hi folks, just wanted to give you a heads-up that your github releases are broken
see https://github.com/N0ich/dialogkey-DF/actions/runs/7046497276/job/19178414666

I think this might be resolved, by changing your workflow file
https://github.com/N0ich/dialogkey-DF/blob/main/.github/workflows/release.yml#L10
replacing `GITHUB_OAUTH: ${{ secrets.GH_TOKEN }}` with `GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}`
Github token is an automatically generated secret for github actions, and from looking at the action log, it looks like it has permissions setup correctly already

as for why you might care? this breaks updates for addon managers that are using github releases as a basis (e.g. cursebreaker or wago-wowup)

**Comment by N0ich** [comment]
Hello,

Thank you! While I don't have much time to test this properly, I was at a loss as to why the action wouldn't work. I stored a GH_TOKEN secret on the repo but it didn't work and the action is still broken.
Thanks for the heads up

**Comment by N0ich** [comment]
Seems the release is indeed fixed and properly usable for wowup :)
