### ISSUE TITLE
1.6.1 Space to Accept Quests

### ISSUE THREAD

**Issue by RadekRatel** [N0ich/dialogkey-DF#39]
This function seems to have stopped working in latest release - instead of accepting or completing the quest, the character just jumps or takes flight instead.

Going back to 1.5.7 restored the functionality.

**Comment by RadekRatel** [comment]
Ok worked it out - it defaults to G apparently, in the new /DialogKey UI . This I think gets globally overwritten by the Ping keybind and function, regardless of which other panes are open.

**Comment by N0ich** [comment]
My bad, I wanted to swap out the default "Space" keybind which causes lots of issues every day with the new users, but I thought it wouldn't overwrite the keybind if it was already bound. 
I'll revert it tonight
