### ISSUE TITLE
Ace errors - likely a missing library

### ISSUE THREAD

**Issue by Sluimerstand** [N0ich/dialogkey-DF#41]
These errors do not occur when BugSack and BugGrabber are enabled. I assume you have done the same thing I did some time ago, where you always test with these two additional addons enabled and never embedded the library into DialogKey itself. :P

**Error 1:**
Message: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
Time: Mon Apr  1 15:48:27 2024
Count: 1
Stack: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/DialogKey/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/DialogKey/libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:12: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "CallbackHandler-1.0"."

**Error 2:**
Message: .../AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua:17: Cannot find a library instance of "AceConfigRegistry-3.0".
Time: Mon Apr  1 15:48:27 2024
Count: 1
Stack: .../AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua:17: Cannot find a library instance of "AceConfigRegistry-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/DialogKey/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/DialogKey/libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:17: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceConfigRegistry-3.0"."

**Error 3:**
Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:8: Cannot find a library instance of "AceConfigRegistry-3.0".
Time: Mon Apr  1 15:48:27 2024
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:8: Cannot find a library instance of "AceConfigRegistry-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/DialogKey/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/DialogKey/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:8: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceConfigRegistry-3.0"."

**Error 4:**
Message: ...ddOns/DialogKey/libs/AceConfig-3.0/AceConfig-3.0.lua:15: Cannot find a library instance of "AceConfigRegistry-3.0".
Time: Mon Apr  1 15:48:27 2024
Count: 1
Stack: ...ddOns/DialogKey/libs/AceConfig-3.0/AceConfig-3.0.lua:15: Cannot find a library instance of "AceConfigRegistry-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/DialogKey/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/DialogKey/libs/AceConfig-3.0/AceConfig-3.0.lua"]:15: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceConfigRegistry-3.0"."

**Error 5:**
Message: Interface/AddOns/DialogKey/main.lua:91: Cannot find a library instance of "AceConfig-3.0".
Time: Mon Apr  1 15:48:27 2024
Count: 1
Stack: Interface/AddOns/DialogKey/main.lua:91: Cannot find a library instance of "AceConfig-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/DialogKey/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/DialogKey/main.lua"]:91: in function <Interface/AddOns/DialogKey/main.lua:42>
[string "=[C]"]: ?
[string "@Interface/AddOns/DialogKey/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/DialogKey/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DialogKey/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/DialogKey/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <.../AddOns/DialogKey/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: (*temporary) = "Cannot find a library instance of "AceConfig-3.0"."

**Comment by FuriousProgrammer** [comment]
This was fixed by https://github.com/N0ich/dialogkey-DF/commit/373854be64685afcf0837141468a44dbc03c5454, but I never pushed the release tag, woops!
