### ISSUE TITLE
Popup click pre-delay

### ISSUE THREAD

**Issue by FuriousProgrammer** [N0ich/dialogkey-DF#9]
Very occasionally, I'll press my DialogKey to accept a quest, and end up accepting a summon request that pops up fractions of a second before I hit the button.

Adding an optional delay before allowing a popup to be clicked (but still e.g. glowing the button to indicate that the input wasn't dropped) could be a useful feature.

**Comment by N0ich** [comment]
I think it would make more sense to implement the order feature and by default complete quests or customs first, as you know which one is opened and such, while popup may appear randomly.
The delay-when-popup-appears could be a bit of a ruin

**Comment by FuriousProgrammer** [comment]
Yeah, I agree.

Switching the default priority to Gossips > Custom > Popups would prevent the issue I'm foreseeing here.
